#!/bin/bash
#PBS -A UCSC0009
#PBS -N output
#PBS -q main           
#PBS -l select=1:ncpus=1:ngpus=1:mem=100GB
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -J 0-5


module load conda  
conda activate py2d_env

echo "Job started at $(date)"
python -u /glade/u/home/tsatoperry/GAD/classification_pipeline.py \
    --job-idx $PBS_ARRAY_INDEX \
    --output-dir /glade/u/home/tsatoperry/GAD/models/
    
echo "Job ended at $(date)"

